### PR TITLE
V2

### LINKED ISSUE #2: Move Random namespace inside index

### LINKED ISSUE #4: Avoid seek leaking by crating local prng
var myrng = new Math.seedrandom('hello.');

### PR DESCRIPTION
**Pull request by dmnsgn**
Changes:

- [x] feat: convert require to import and module.exports to exports
- [x] test: add missing test dependency tape and pex-geom
- [x] docs: convert test to esm
- [x] build: update dependencies (new seedrandom api and new breaking change simplex noise version)
- [x] refactor: move everything to index.js (#2)
- [x] feat: use Number.MAX_SAFE_INTEGER
- [x] test: update for recent pex-math and pex-geom
- [x] perf: remove intermediary const declaration in vec3InAABB
- [x] feat: use default argument values
- [x] feat: add FBM

TBD:

- [x] feat: use local prng (#4): does it means we can't Math.random and should only use random.float()?

Closes #2 
Closes #4

### CODE REVIEW

**Comment by vorg** [comment]
About the random prng Replied on the issue https://github.com/pex-gl/pex-random/issues/4

**Comment by dmnsgn** [comment]
TODO @dmnsgn add some notes about:
- Input coordinates bigger than 2^31 may not result in a noisy output anymore.
- Similar seeds might not result in different values for the same position in noise (see test)

**Comment by vorg** [comment]
Did we change seedrandom compared to older versions? Is it their issue?

**Comment by dmnsgn** [comment]
It is a seedrandom "standard ARC4 key scheduler cycles short keys" issue, we just never noticed as the test were always using the same 0/1 seeds:
https://github.com/pex-gl/pex-random/blob/f199ef867c416ec45c491b9ff84b8b9e3e94a13c/test/Random.js#L245-L247

While I rewrote it to be i/i+1:
https://github.com/pex-gl/pex-random/blob/9293bd282bba56a909facd1f79cee9d3a055e51d/test/index.js#L339-L341

<details>
  <summary>Test here</summary>
    
  Update Random.js code to following and run `node --test` in v1:
  
  ```js
  var { describe, it } = require("node:test");
  var assert = require("assert");
  var rnd = require("../");
  
  describe("Random", function () {
    describe("noise2(x, y)", function () {
      it("should return the different value for the same x,y", function () {
        for (var i = 0; i < 100; i++) {
          var x = 100 * Math.random();
          var y = 100 * Math.random();
          rnd.seed(i);
          var r1 = rnd.noise2(x, y);
          rnd.seed(i + 1);
          var r2 = rnd.noise2(x, y);
          assert.notEqual(r1, r2);
        }
      });
    });
  });
  ```
</details>

**Pull request merged**
